[DEBUG]	2022-01-11 13:02:55,969	service_stock	[base_url] http://127.0.0.1:8000	process:10	thread:281473697025664
[DEBUG]	2022-01-11 13:02:55,976	create_service_stock	[context] {'area_name': '神奈川県相模原市', 'base_url': 'http://127.0.0.1:8000', 'serv_items': {0: <ServiceItemForm bound=False, valid=Unknown, fields=(phrase;is_app_con)>}, 'phrase': None}	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:02:56,402	log	Not Found: /static/debug_toolbar/css/toolbar.css	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:02:56,456	log	Not Found: /static/debug_toolbar/js/toolbar.js	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:02:56,542	log	Not Found: /static/debug_toolbar/css/toolbar.css	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:02:56,612	log	Not Found: /static/debug_toolbar/css/print.css	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:02:56,643	log	Not Found: /static/debug_toolbar/js/toolbar.js	process:10	thread:281473697025664
[DEBUG]	2022-01-11 13:02:59,230	service_name	[get_name_starts() word_part] None	process:10	thread:281473697025664
[DEBUG]	2022-01-11 13:02:59,248	service_name	[_get_word_parts() word_parts] []	process:10	thread:281473697025664
[DEBUG]	2022-01-11 13:02:59,263	service_name	[get_name_ends() word_part] 届け出書	process:10	thread:281473697025664
[DEBUG]	2022-01-11 13:02:59,271	service_name	[_get_word_parts() word_parts] <QuerySet [<Name_End: 届け出書>, <Name_End: 届出書>, <Name_End: 届出>, <Name_End: 届け出>, <Name_End: 届>, <Name_End: 届け>]>	process:10	thread:281473697025664
[DEBUG]	2022-01-11 13:02:59,321	service_name	[fuzzy_search() serv_names] <QuerySet [<Service_Name: 住民異動届>, <Service_Name: 婚姻届>]>	process:10	thread:281473697025664
[DEBUG]	2022-01-11 13:02:59,335	service_stock	[get_serv_stocks() serv_names,area_name] <QuerySet [<Service_Name: 住民異動届>, <Service_Name: 婚姻届>]> 神奈川県相模原市	process:10	thread:281473697025664
[DEBUG]	2022-01-11 13:02:59,432	service_stock	[fuzzy_search() serv_stocks] [<Service_Stock: 住民異動届>, <Service_Stock: 婚姻届>]	process:10	thread:281473697025664
[DEBUG]	2022-01-11 13:02:59,434	register_used_service	[phrases] ['住民異動届', '婚姻届']	process:10	thread:281473697025664
[DEBUG]	2022-01-11 13:03:04,505	service_stock_form	[serv_name] 婚姻届	process:10	thread:281473697025664
[DEBUG]	2022-01-11 13:03:04,514	service_stock_form	[name] 婚姻届	process:10	thread:281473697025664
[DEBUG]	2022-01-11 13:03:09,616	service_stock_form	[serv_name] 婚姻届	process:10	thread:281473697025664
[DEBUG]	2022-01-11 13:03:09,617	service_stock_form	[_type] {'_type': 'serv_name'}	process:10	thread:281473697025664
[DEBUG]	2022-01-11 13:03:09,618	service_stock_form	[serv_items] ['神奈川県相模原市', '婚姻届', '氏名']	process:10	thread:281473697025664
[ERROR]	2022-01-11 13:03:09,676	log	Internal Server Error: /peace_keeping/validate_serv/	process:10	thread:281473697025664
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "./peace_keeping/views/create_service_stock.py", line 32, in post
    serv_name, serv_items = ServiceStockForm.clean_fields(request.POST)
  File "./peace_keeping/forms/service_stock_form.py", line 26, in clean_fields
    serv_items = cls._clean_serv_items(inputs)
  File "./peace_keeping/forms/service_stock_form.py", line 58, in _clean_serv_items
    serv_item = Service_Item.objects.filter(phrase=_serv_item).get()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 439, in get
    raise self.model.DoesNotExist(
words.models.service_item.Service_Item.DoesNotExist: Service_Item matching query does not exist.
[WARNING]	2022-01-11 13:03:10,218	log	Not Found: /static/debug_toolbar/js/toolbar.js	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:03:10,275	log	Not Found: /static/debug_toolbar/css/toolbar.css	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:03:10,332	log	Not Found: /static/debug_toolbar/css/print.css	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:03:10,413	log	Not Found: /static/debug_toolbar/js/toolbar.js	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:03:42,320	log	Not Found: /static/debug_toolbar/css/print.css	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:03:42,551	log	Not Found: /static/debug_toolbar/css/toolbar.css	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:03:42,591	log	Not Found: /static/debug_toolbar/js/toolbar.js	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:03:43,141	log	Not Found: /static/debug_toolbar/css/print.css	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:03:43,196	log	Not Found: /static/debug_toolbar/js/toolbar.js	process:10	thread:281473697025664
[DEBUG]	2022-01-11 13:04:50,598	service_stock	[base_url] http://127.0.0.1:8000	process:10	thread:281473697025664
[DEBUG]	2022-01-11 13:04:50,623	create_service_stock	[context] {'area_name': '神奈川県相模原市', 'base_url': 'http://127.0.0.1:8000', 'serv_items': {0: <ServiceItemForm bound=False, valid=Unknown, fields=(phrase;is_app_con)>}, 'phrase': None}	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:04:50,867	log	Not Found: /static/debug_toolbar/css/toolbar.css	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:04:50,965	log	Not Found: /static/debug_toolbar/js/toolbar.js	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:04:51,039	log	Not Found: /static/debug_toolbar/css/print.css	process:10	thread:281473697025664
[DEBUG]	2022-01-11 13:04:51,488	service_stock	[base_url] http://127.0.0.1:8000	process:10	thread:281473697025664
[DEBUG]	2022-01-11 13:04:51,492	create_service_stock	[context] {'area_name': '神奈川県相模原市', 'base_url': 'http://127.0.0.1:8000', 'serv_items': {0: <ServiceItemForm bound=False, valid=Unknown, fields=(phrase;is_app_con)>}, 'phrase': None}	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:04:51,643	log	Not Found: /static/debug_toolbar/css/toolbar.css	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:04:51,893	log	Not Found: /static/debug_toolbar/js/toolbar.js	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:04:51,958	log	Not Found: /static/debug_toolbar/css/toolbar.css	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:04:52,050	log	Not Found: /static/debug_toolbar/css/print.css	process:10	thread:281473697025664
[DEBUG]	2022-01-11 13:04:52,060	service_stock	[base_url] http://127.0.0.1:8000	process:10	thread:281473697025664
[DEBUG]	2022-01-11 13:04:52,064	create_service_stock	[context] {'area_name': '神奈川県相模原市', 'base_url': 'http://127.0.0.1:8000', 'serv_items': {0: <ServiceItemForm bound=False, valid=Unknown, fields=(phrase;is_app_con)>}, 'phrase': None}	process:10	thread:281473697025664
[DEBUG]	2022-01-11 13:04:52,160	service_stock	[base_url] http://127.0.0.1:8000	process:10	thread:281473697025664
[DEBUG]	2022-01-11 13:04:52,161	create_service_stock	[context] {'area_name': '神奈川県相模原市', 'base_url': 'http://127.0.0.1:8000', 'serv_items': {0: <ServiceItemForm bound=False, valid=Unknown, fields=(phrase;is_app_con)>}, 'phrase': None}	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:04:52,269	log	Not Found: /static/debug_toolbar/js/toolbar.js	process:10	thread:281473697025664
[DEBUG]	2022-01-11 13:04:52,272	service_stock	[base_url] http://127.0.0.1:8000	process:10	thread:281473697025664
[DEBUG]	2022-01-11 13:04:52,278	create_service_stock	[context] {'area_name': '神奈川県相模原市', 'base_url': 'http://127.0.0.1:8000', 'serv_items': {0: <ServiceItemForm bound=False, valid=Unknown, fields=(phrase;is_app_con)>}, 'phrase': None}	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:04:52,416	log	Not Found: /static/debug_toolbar/css/toolbar.css	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:04:52,480	log	Not Found: /static/debug_toolbar/js/toolbar.js	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:04:52,526	log	Not Found: /static/debug_toolbar/css/toolbar.css	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:04:52,601	log	Not Found: /static/debug_toolbar/css/print.css	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:04:52,638	log	Not Found: /static/debug_toolbar/js/toolbar.js	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:05:07,016	log	Not Found: /static/debug_toolbar/css/print.css	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:05:07,229	log	Not Found: /static/debug_toolbar/css/toolbar.css	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:05:07,260	log	Not Found: /static/debug_toolbar/js/toolbar.js	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:05:07,393	log	Not Found: /static/debug_toolbar/css/print.css	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:05:07,425	log	Not Found: /static/debug_toolbar/js/toolbar.js	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:13:02,264	log	Not Found: /	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:13:02,656	log	Not Found: /static/debug_toolbar/css/toolbar.css	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:13:02,718	log	Not Found: /static/debug_toolbar/js/toolbar.js	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:13:02,790	log	Not Found: /static/debug_toolbar/css/print.css	process:10	thread:281473697025664
[WARNING]	2022-01-11 13:13:02,852	log	Not Found: /static/debug_toolbar/js/toolbar.js	process:10	thread:281473697025664
[DEBUG]	2022-01-11 16:56:23,054	service_stock	[base_url] http://127.0.0.1:8000	process:10	thread:281473697025664
[DEBUG]	2022-01-11 16:56:23,140	create_service_stock	[context] {'area_name': '神奈川県相模原市', 'base_url': 'http://127.0.0.1:8000', 'serv_items': {0: <ServiceItemForm bound=False, valid=Unknown, fields=(phrase;is_app_con)>}, 'phrase': None}	process:10	thread:281473697025664
[WARNING]	2022-01-11 16:56:23,770	log	Not Found: /static/debug_toolbar/css/toolbar.css	process:10	thread:281473697025664
[WARNING]	2022-01-11 16:56:23,843	log	Not Found: /static/debug_toolbar/js/toolbar.js	process:10	thread:281473697025664
[WARNING]	2022-01-11 16:56:23,949	log	Not Found: /static/debug_toolbar/css/print.css	process:10	thread:281473697025664
[DEBUG]	2022-01-11 16:56:28,552	service_stock	[base_url] http://127.0.0.1:8000	process:10	thread:281473697025664
[DEBUG]	2022-01-11 16:56:28,563	create_service_stock	[context] {'area_name': '神奈川県相模原市', 'base_url': 'http://127.0.0.1:8000', 'serv_items': {0: <ServiceItemForm bound=False, valid=Unknown, fields=(phrase;is_app_con)>}, 'phrase': None}	process:10	thread:281473697025664
[WARNING]	2022-01-11 16:56:28,817	log	Not Found: /static/debug_toolbar/css/toolbar.css	process:10	thread:281473697025664
[WARNING]	2022-01-11 16:56:28,877	log	Not Found: /static/debug_toolbar/js/toolbar.js	process:10	thread:281473697025664
[WARNING]	2022-01-11 16:56:29,013	log	Not Found: /static/debug_toolbar/css/print.css	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:22,964	service_name	[get_name_starts() word_part] None	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:23,103	service_name	[_get_word_parts() word_parts] []	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:23,116	service_name	[get_name_ends() word_part] 届け出書	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:23,124	service_name	[_get_word_parts() word_parts] <QuerySet [<Name_End: 届け出書>, <Name_End: 届出書>, <Name_End: 届出>, <Name_End: 届け出>, <Name_End: 届>, <Name_End: 届け>]>	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:23,167	service_name	[fuzzy_search() serv_names] <QuerySet [<Service_Name: 住民異動届>, <Service_Name: 婚姻届>]>	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:23,183	service_stock	[get_serv_stocks() serv_names,area_name] <QuerySet [<Service_Name: 住民異動届>, <Service_Name: 婚姻届>]> 神奈川県相模原市	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:23,240	service_stock	[fuzzy_search() serv_stocks] [<Service_Stock: 住民異動届>, <Service_Stock: 婚姻届>]	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:23,242	register_used_service	[phrases] ['住民異動届', '婚姻届']	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:24,802	service_name	[get_name_starts() word_part] None	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:24,804	service_name	[_get_word_parts() word_parts] []	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:24,813	service_name	[get_name_ends() word_part] 届け出書	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:24,822	service_name	[_get_word_parts() word_parts] <QuerySet [<Name_End: 届け出書>, <Name_End: 届出書>, <Name_End: 届出>, <Name_End: 届け出>, <Name_End: 届>, <Name_End: 届け>]>	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:24,854	service_name	[fuzzy_search() serv_names] <QuerySet [<Service_Name: 住民異動届>, <Service_Name: 婚姻届>]>	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:24,880	service_stock	[get_serv_stocks() serv_names,area_name] <QuerySet [<Service_Name: 住民異動届>, <Service_Name: 婚姻届>]> 神奈川県相模原市	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:24,940	service_stock	[fuzzy_search() serv_stocks] [<Service_Stock: 住民異動届>, <Service_Stock: 婚姻届>]	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:24,944	register_used_service	[phrases] ['住民異動届', '婚姻届']	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:25,158	service_name	[get_name_starts() word_part] None	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:25,159	service_name	[_get_word_parts() word_parts] []	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:25,164	service_name	[get_name_ends() word_part] 届け出書	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:25,169	service_name	[_get_word_parts() word_parts] <QuerySet [<Name_End: 届け出書>, <Name_End: 届出書>, <Name_End: 届出>, <Name_End: 届け出>, <Name_End: 届>, <Name_End: 届け>]>	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:25,187	service_name	[fuzzy_search() serv_names] <QuerySet [<Service_Name: 住民異動届>, <Service_Name: 婚姻届>]>	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:25,201	service_stock	[get_serv_stocks() serv_names,area_name] <QuerySet [<Service_Name: 住民異動届>, <Service_Name: 婚姻届>]> 神奈川県相模原市	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:25,235	service_stock	[fuzzy_search() serv_stocks] [<Service_Stock: 住民異動届>, <Service_Stock: 婚姻届>]	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:25,237	register_used_service	[phrases] ['住民異動届', '婚姻届']	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:26,737	service_name	[get_name_starts() word_part] None	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:26,739	service_name	[_get_word_parts() word_parts] []	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:26,751	service_name	[get_name_ends() word_part] 届け出書	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:26,758	service_name	[_get_word_parts() word_parts] <QuerySet [<Name_End: 届け出書>, <Name_End: 届出書>, <Name_End: 届出>, <Name_End: 届け出>, <Name_End: 届>, <Name_End: 届け>]>	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:26,781	service_name	[fuzzy_search() serv_names] <QuerySet [<Service_Name: 住民異動届>, <Service_Name: 婚姻届>]>	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:26,796	service_stock	[get_serv_stocks() serv_names,area_name] <QuerySet [<Service_Name: 住民異動届>, <Service_Name: 婚姻届>]> 神奈川県相模原市	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:26,835	service_stock	[fuzzy_search() serv_stocks] [<Service_Stock: 住民異動届>, <Service_Stock: 婚姻届>]	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:26,836	register_used_service	[phrases] ['住民異動届', '婚姻届']	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:39,907	service_name	[get_name_starts() word_part] None	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:39,914	service_name	[_get_word_parts() word_parts] []	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:39,921	service_name	[get_name_ends() word_part] 届け出書	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:39,927	service_name	[_get_word_parts() word_parts] <QuerySet [<Name_End: 届け出書>, <Name_End: 届出書>, <Name_End: 届出>, <Name_End: 届け出>, <Name_End: 届>, <Name_End: 届け>]>	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:39,945	service_name	[fuzzy_search() serv_names] <QuerySet [<Service_Name: 住民異動届>, <Service_Name: 婚姻届>]>	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:39,959	service_stock	[get_serv_stocks() serv_names,area_name] <QuerySet [<Service_Name: 住民異動届>, <Service_Name: 婚姻届>]> 神奈川県相模原市	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:39,996	service_stock	[fuzzy_search() serv_stocks] [<Service_Stock: 住民異動届>, <Service_Stock: 婚姻届>]	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:39:39,997	register_used_service	[phrases] ['住民異動届', '婚姻届']	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:40:06,435	service_stock_form	[serv_name] 届	process:10	thread:281473697025664
[DEBUG]	2022-01-11 21:40:06,442	service_stock_form	[name] 届	process:10	thread:281473697025664
[ERROR]	2022-01-11 21:40:06,573	log	Internal Server Error: /peace_keeping/validate_serv/	process:10	thread:281473697025664
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "./peace_keeping/views/create_service_stock.py", line 32, in post
    serv_name, serv_items = ServiceStockForm.clean_fields(request.POST)
  File "./peace_keeping/forms/service_stock_form.py", line 25, in clean_fields
    serv_name = cls._clean_serv_name(serv_name)
  File "./peace_keeping/forms/service_stock_form.py", line 40, in _clean_serv_name
    serv_name = Service_Name.objects.select_related('name_start').filter(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 439, in get
    raise self.model.DoesNotExist(
words.models.service_name.Service_Name.DoesNotExist: Service_Name matching query does not exist.
[WARNING]	2022-01-11 21:40:08,688	log	Not Found: /static/debug_toolbar/css/toolbar.css	process:10	thread:281473697025664
[WARNING]	2022-01-11 21:40:08,951	log	Not Found: /static/debug_toolbar/js/toolbar.js	process:10	thread:281473697025664
[WARNING]	2022-01-11 21:40:09,034	log	Not Found: /static/debug_toolbar/css/print.css	process:10	thread:281473697025664
[DEBUG]	2022-01-11 22:04:23,694	service_stock	[base_url] http://127.0.0.1:8000	process:10	thread:281473697025664
[DEBUG]	2022-01-11 22:04:23,762	create_service_stock	[context] {'area_name': '神奈川県相模原市', 'base_url': 'http://127.0.0.1:8000', 'serv_items': {0: <ServiceItemForm bound=False, valid=Unknown, fields=(phrase;is_app_con)>}, 'phrase': None}	process:10	thread:281473697025664
[WARNING]	2022-01-11 22:04:24,264	log	Not Found: /static/debug_toolbar/css/toolbar.css	process:10	thread:281473697025664
[WARNING]	2022-01-11 22:04:24,345	log	Not Found: /static/debug_toolbar/js/toolbar.js	process:10	thread:281473697025664
[WARNING]	2022-01-11 22:04:24,515	log	Not Found: /static/debug_toolbar/css/print.css	process:10	thread:281473697025664
[WARNING]	2022-01-11 22:04:24,574	log	Not Found: /static/debug_toolbar/css/toolbar.css	process:10	thread:281473697025664
[WARNING]	2022-01-11 22:04:24,717	log	Not Found: /static/debug_toolbar/js/toolbar.js	process:10	thread:281473697025664
[DEBUG]	2022-01-11 22:04:55,329	service_stock	[base_url] http://127.0.0.1:8000	process:10	thread:281473697025664
[DEBUG]	2022-01-11 22:04:55,344	create_service_stock	[context] {'area_name': '神奈川県相模原市', 'base_url': 'http://127.0.0.1:8000', 'serv_items': {0: <ServiceItemForm bound=False, valid=Unknown, fields=(phrase;is_app_con)>}, 'phrase': None}	process:10	thread:281473697025664
[WARNING]	2022-01-11 22:04:55,676	log	Not Found: /static/debug_toolbar/css/toolbar.css	process:10	thread:281473697025664
[WARNING]	2022-01-11 22:04:55,900	log	Not Found: /static/debug_toolbar/js/toolbar.js	process:10	thread:281473697025664
[WARNING]	2022-01-11 22:04:56,112	log	Not Found: /static/debug_toolbar/css/print.css	process:10	thread:281473697025664
[DEBUG]	2022-01-11 22:12:54,962	service_stock	[base_url] http://127.0.0.1:8000	process:13	thread:281473015848576
[DEBUG]	2022-01-11 22:12:54,974	create_service_stock	[context] {'area_name': '神奈川県相模原市', 'base_url': 'http://127.0.0.1:8000', 'serv_items': {0: <ServiceItemForm bound=False, valid=Unknown, fields=(phrase;is_app_con)>}, 'phrase': None}	process:13	thread:281473015848576
[ERROR]	2022-01-11 22:12:55,556	log	Internal Server Error: /peace_keeping/create_serv/神奈川県相模原市/	process:13	thread:281473015848576
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/debug_toolbar/middleware.py", line 74, in __call__
    rendered = toolbar.render_toolbar()
  File "/usr/local/lib/python3.8/site-packages/debug_toolbar/toolbar.py", line 70, in render_toolbar
    return render_to_string("debug_toolbar/base.html", context)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: debug_toolbar/base.html
[DEBUG]	2022-01-11 22:13:46,915	service_stock	[base_url] http://127.0.0.1:8000	process:16	thread:281473333280384
[DEBUG]	2022-01-11 22:13:46,917	create_service_stock	[context] {'area_name': '神奈川県相模原市', 'base_url': 'http://127.0.0.1:8000', 'serv_items': {0: <ServiceItemForm bound=False, valid=Unknown, fields=(phrase;is_app_con)>}, 'phrase': None}	process:16	thread:281473333280384
[ERROR]	2022-01-11 22:13:47,048	log	Internal Server Error: /peace_keeping/create_serv/神奈川県相模原市/	process:16	thread:281473333280384
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/debug_toolbar/middleware.py", line 74, in __call__
    rendered = toolbar.render_toolbar()
  File "/usr/local/lib/python3.8/site-packages/debug_toolbar/toolbar.py", line 70, in render_toolbar
    return render_to_string("debug_toolbar/base.html", context)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: debug_toolbar/base.html
[DEBUG]	2022-01-11 22:14:18,074	service_stock	[base_url] http://127.0.0.1:8000	process:19	thread:281473320803968
[DEBUG]	2022-01-11 22:14:18,076	create_service_stock	[context] {'area_name': '神奈川県相模原市', 'base_url': 'http://127.0.0.1:8000', 'serv_items': {0: <ServiceItemForm bound=False, valid=Unknown, fields=(phrase;is_app_con)>}, 'phrase': None}	process:19	thread:281473320803968
[DEBUG]	2022-01-11 22:47:48,410	service_stock	[base_url] http://127.0.0.1:8000	process:19	thread:281473320803968
[DEBUG]	2022-01-11 22:47:48,470	create_service_stock	[context] {'area_name': '神奈川県相模原市', 'base_url': 'http://127.0.0.1:8000', 'serv_items': {0: <ServiceItemForm bound=False, valid=Unknown, fields=(phrase;is_app_con)>}, 'phrase': None}	process:19	thread:281473320803968
[DEBUG]	2022-01-11 22:47:58,355	service_stock	[base_url] http://127.0.0.1:8000	process:19	thread:281473320803968
[DEBUG]	2022-01-11 22:47:58,379	create_service_stock	[context] {'area_name': '神奈川県相模原市', 'base_url': 'http://127.0.0.1:8000', 'serv_items': {0: <ServiceItemForm bound=False, valid=Unknown, fields=(phrase;is_app_con)>}, 'phrase': None}	process:19	thread:281473320803968
[DEBUG]	2022-01-12 08:42:56,946	service_stock	[base_url] http://127.0.0.1:8000	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:42:56,949	create_service_stock	[context] {'area_name': '神奈川県相模原市', 'base_url': 'http://127.0.0.1:8000', 'serv_items': {0: <ServiceItemForm bound=False, valid=Unknown, fields=(phrase;is_app_con)>}, 'phrase': None}	process:9	thread:281472983924352
[WARNING]	2022-01-12 08:42:57,315	log	Not Found: /favicon.ico	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:43:14,146	service_stock	[base_url] http://127.0.0.1:8000	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:43:14,162	create_service_stock	[context] {'area_name': '神奈川県相模原市', 'base_url': 'http://127.0.0.1:8000', 'serv_items': {0: <ServiceItemForm bound=False, valid=Unknown, fields=(phrase;is_app_con)>}, 'phrase': None}	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:43:21,233	service_stock	[base_url] http://127.0.0.1:8000	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:43:21,249	create_service_stock	[context] {'area_name': '神奈川県相模原市', 'base_url': 'http://127.0.0.1:8000', 'serv_items': {0: <ServiceItemForm bound=False, valid=Unknown, fields=(phrase;is_app_con)>}, 'phrase': None}	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:43:22,099	service_stock	[base_url] http://127.0.0.1:8000	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:43:22,102	create_service_stock	[context] {'area_name': '神奈川県相模原市', 'base_url': 'http://127.0.0.1:8000', 'serv_items': {0: <ServiceItemForm bound=False, valid=Unknown, fields=(phrase;is_app_con)>}, 'phrase': None}	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:43:22,565	service_stock	[base_url] http://127.0.0.1:8000	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:43:22,568	create_service_stock	[context] {'area_name': '神奈川県相模原市', 'base_url': 'http://127.0.0.1:8000', 'serv_items': {0: <ServiceItemForm bound=False, valid=Unknown, fields=(phrase;is_app_con)>}, 'phrase': None}	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:43:22,766	service_stock	[base_url] http://127.0.0.1:8000	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:43:22,768	create_service_stock	[context] {'area_name': '神奈川県相模原市', 'base_url': 'http://127.0.0.1:8000', 'serv_items': {0: <ServiceItemForm bound=False, valid=Unknown, fields=(phrase;is_app_con)>}, 'phrase': None}	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:43:22,942	service_stock	[base_url] http://127.0.0.1:8000	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:43:22,945	create_service_stock	[context] {'area_name': '神奈川県相模原市', 'base_url': 'http://127.0.0.1:8000', 'serv_items': {0: <ServiceItemForm bound=False, valid=Unknown, fields=(phrase;is_app_con)>}, 'phrase': None}	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:43:24,974	service_name	[get_name_starts() word_part] None	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:43:24,977	service_name	[_get_word_parts() word_parts] []	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:43:24,987	service_name	[get_name_ends() word_part] 届け出書	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:43:24,992	service_name	[_get_word_parts() word_parts] <QuerySet [<Name_End: 届け出書>, <Name_End: 届出書>, <Name_End: 届出>, <Name_End: 届け出>, <Name_End: 届>, <Name_End: 届け>]>	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:43:25,030	service_name	[fuzzy_search() serv_names] <QuerySet [<Service_Name: 住民異動届>, <Service_Name: 婚姻届>]>	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:43:25,042	service_stock	[get_serv_stocks() serv_names,area_name] <QuerySet [<Service_Name: 住民異動届>, <Service_Name: 婚姻届>]> 神奈川県相模原市	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:43:25,113	service_stock	[fuzzy_search() serv_stocks] [<Service_Stock: 住民異動届>, <Service_Stock: 婚姻届>]	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:43:25,114	register_used_service	[phrases] ['住民異動届', '婚姻届']	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:43:57,967	service_stock_form	[serv_name] 住民異動届	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:43:57,975	service_stock_form	[name] 住民異動届	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:44:03,052	service_stock_form	[serv_name] 住民異動届	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:44:03,054	service_stock_form	[_type] {'_type': 'serv_name'}	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:44:03,055	service_stock_form	[serv_items] ['神奈川県相模原市', '住民異動届', '氏名']	process:9	thread:281472983924352
[ERROR]	2022-01-12 08:44:03,106	log	Internal Server Error: /peace_keeping/validate_serv/	process:9	thread:281472983924352
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "./peace_keeping/views/create_service_stock.py", line 32, in post
    serv_name, serv_items = ServiceStockForm.clean_fields(request.POST)
  File "./peace_keeping/forms/service_stock_form.py", line 26, in clean_fields
    serv_items = cls._clean_serv_items(inputs)
  File "./peace_keeping/forms/service_stock_form.py", line 58, in _clean_serv_items
    serv_item = Service_Item.objects.filter(phrase=_serv_item).get()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 439, in get
    raise self.model.DoesNotExist(
words.models.service_item.Service_Item.DoesNotExist: Service_Item matching query does not exist.
[DEBUG]	2022-01-12 08:44:03,111	service_stock_form	[serv_name] 住民異動届	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:44:03,112	service_stock_form	[name] 住民異動届	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:44:03,120	service_stock_form	[serv_name] 住民異動届	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:44:03,121	service_stock_form	[_type] {'_type': 'serv_name'}	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:44:03,122	service_stock_form	[serv_items] ['神奈川県相模原市', '住民異動届', '氏名']	process:9	thread:281472983924352
[ERROR]	2022-01-12 08:44:03,140	log	Internal Server Error: /peace_keeping/validate_serv/	process:9	thread:281472983924352
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "./peace_keeping/views/create_service_stock.py", line 32, in post
    serv_name, serv_items = ServiceStockForm.clean_fields(request.POST)
  File "./peace_keeping/forms/service_stock_form.py", line 26, in clean_fields
    serv_items = cls._clean_serv_items(inputs)
  File "./peace_keeping/forms/service_stock_form.py", line 58, in _clean_serv_items
    serv_item = Service_Item.objects.filter(phrase=_serv_item).get()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 439, in get
    raise self.model.DoesNotExist(
words.models.service_item.Service_Item.DoesNotExist: Service_Item matching query does not exist.
[DEBUG]	2022-01-12 08:44:03,142	service_stock_form	[serv_name] 住民異動届	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:44:03,143	service_stock_form	[name] 住民異動届	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:44:03,153	service_stock_form	[serv_name] 住民異動届	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:44:03,154	service_stock_form	[_type] {'_type': 'serv_name'}	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:44:03,155	service_stock_form	[serv_items] ['神奈川県相模原市', '住民異動届', '氏名']	process:9	thread:281472983924352
[ERROR]	2022-01-12 08:44:03,173	log	Internal Server Error: /peace_keeping/validate_serv/	process:9	thread:281472983924352
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "./peace_keeping/views/create_service_stock.py", line 32, in post
    serv_name, serv_items = ServiceStockForm.clean_fields(request.POST)
  File "./peace_keeping/forms/service_stock_form.py", line 26, in clean_fields
    serv_items = cls._clean_serv_items(inputs)
  File "./peace_keeping/forms/service_stock_form.py", line 58, in _clean_serv_items
    serv_item = Service_Item.objects.filter(phrase=_serv_item).get()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 439, in get
    raise self.model.DoesNotExist(
words.models.service_item.Service_Item.DoesNotExist: Service_Item matching query does not exist.
[DEBUG]	2022-01-12 08:47:34,022	service_stock	[base_url] http://127.0.0.1:8000	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:47:34,034	create_service_stock	[context] {'area_name': '神奈川県相模原市', 'base_url': 'http://127.0.0.1:8000', 'serv_items': {0: <ServiceItemForm bound=False, valid=Unknown, fields=(phrase;is_app_con)>}, 'phrase': None}	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:47:34,514	service_stock	[base_url] http://127.0.0.1:8000	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:47:34,517	create_service_stock	[context] {'area_name': '神奈川県相模原市', 'base_url': 'http://127.0.0.1:8000', 'serv_items': {0: <ServiceItemForm bound=False, valid=Unknown, fields=(phrase;is_app_con)>}, 'phrase': None}	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:47:34,709	service_stock	[base_url] http://127.0.0.1:8000	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:47:34,712	create_service_stock	[context] {'area_name': '神奈川県相模原市', 'base_url': 'http://127.0.0.1:8000', 'serv_items': {0: <ServiceItemForm bound=False, valid=Unknown, fields=(phrase;is_app_con)>}, 'phrase': None}	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:47:34,904	service_stock	[base_url] http://127.0.0.1:8000	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:47:34,905	create_service_stock	[context] {'area_name': '神奈川県相模原市', 'base_url': 'http://127.0.0.1:8000', 'serv_items': {0: <ServiceItemForm bound=False, valid=Unknown, fields=(phrase;is_app_con)>}, 'phrase': None}	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:47:35,061	service_stock	[base_url] http://127.0.0.1:8000	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:47:35,063	create_service_stock	[context] {'area_name': '神奈川県相模原市', 'base_url': 'http://127.0.0.1:8000', 'serv_items': {0: <ServiceItemForm bound=False, valid=Unknown, fields=(phrase;is_app_con)>}, 'phrase': None}	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:53:33,164	service_stock	[base_url] http://127.0.0.1:8000	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:53:33,179	create_service_stock	[context] {'area_name': '神奈川県相模原市', 'base_url': 'http://127.0.0.1:8000', 'serv_items': {0: <ServiceItemForm bound=False, valid=Unknown, fields=(phrase;is_app_con)>}, 'phrase': None}	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:53:35,473	service_stock	[base_url] http://127.0.0.1:8000	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:53:35,481	create_service_stock	[context] {'area_name': '神奈川県相模原市', 'base_url': 'http://127.0.0.1:8000', 'serv_items': {0: <ServiceItemForm bound=False, valid=Unknown, fields=(phrase;is_app_con)>}, 'phrase': None}	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:53:38,195	service_name	[get_name_starts() word_part] None	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:53:38,197	service_name	[_get_word_parts() word_parts] []	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:53:38,203	service_name	[get_name_ends() word_part] 届け出書	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:53:38,208	service_name	[_get_word_parts() word_parts] <QuerySet [<Name_End: 届け出書>, <Name_End: 届出書>, <Name_End: 届出>, <Name_End: 届け出>, <Name_End: 届>, <Name_End: 届け>]>	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:53:38,231	service_name	[fuzzy_search() serv_names] <QuerySet [<Service_Name: 住民異動届>, <Service_Name: 婚姻届>]>	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:53:38,246	service_stock	[get_serv_stocks() serv_names,area_name] <QuerySet [<Service_Name: 住民異動届>, <Service_Name: 婚姻届>]> 神奈川県相模原市	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:53:38,266	service_stock	[fuzzy_search() serv_stocks] [<Service_Stock: 住民異動届>, <Service_Stock: 婚姻届>]	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:53:38,267	register_used_service	[phrases] ['住民異動届', '婚姻届']	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:53:40,898	service_stock_form	[serv_name] 婚姻届	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:53:40,901	service_stock_form	[name] 婚姻届	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:53:40,931	service_stock_form	[serv_name] 婚姻届	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:53:40,933	service_stock_form	[_type] {'_type': 'serv_name'}	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:53:40,936	service_stock_form	[serv_items] ['神奈川県相模原市', '婚姻届', '氏名']	process:9	thread:281472983924352
[ERROR]	2022-01-12 08:53:40,974	log	Internal Server Error: /peace_keeping/validate_serv/	process:9	thread:281472983924352
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "./peace_keeping/views/create_service_stock.py", line 32, in post
    serv_name, serv_items = ServiceStockForm.clean_fields(request.POST)
  File "./peace_keeping/forms/service_stock_form.py", line 26, in clean_fields
    serv_items = cls._clean_serv_items(inputs)
  File "./peace_keeping/forms/service_stock_form.py", line 58, in _clean_serv_items
    serv_item = Service_Item.objects.filter(phrase=_serv_item).get()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 439, in get
    raise self.model.DoesNotExist(
words.models.service_item.Service_Item.DoesNotExist: Service_Item matching query does not exist.
[DEBUG]	2022-01-12 08:54:41,458	service_stock_form	[serv_name] 婚姻届	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:54:41,465	service_stock_form	[name] 婚姻届	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:54:41,495	service_stock_form	[serv_name] 婚姻届	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:54:41,497	service_stock_form	[_type] {'_type': 'serv_name'}	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:54:41,498	service_stock_form	[serv_items] ['神奈川県相模原市', '婚姻届', '氏名']	process:9	thread:281472983924352
[ERROR]	2022-01-12 08:54:41,524	log	Internal Server Error: /peace_keeping/validate_serv/	process:9	thread:281472983924352
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "./peace_keeping/views/create_service_stock.py", line 32, in post
    serv_name, serv_items = ServiceStockForm.clean_fields(request.POST)
  File "./peace_keeping/forms/service_stock_form.py", line 26, in clean_fields
    serv_items = cls._clean_serv_items(inputs)
  File "./peace_keeping/forms/service_stock_form.py", line 58, in _clean_serv_items
    serv_item = Service_Item.objects.filter(phrase=_serv_item).get()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 439, in get
    raise self.model.DoesNotExist(
words.models.service_item.Service_Item.DoesNotExist: Service_Item matching query does not exist.
[DEBUG]	2022-01-12 08:54:48,645	service_stock_form	[serv_name] 婚姻届	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:54:48,653	service_stock_form	[name] 婚姻届	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:54:48,679	service_stock_form	[serv_name] 婚姻届	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:54:48,681	service_stock_form	[_type] {'_type': 'serv_name'}	process:9	thread:281472983924352
[DEBUG]	2022-01-12 08:54:48,682	service_stock_form	[serv_items] ['神奈川県相模原市', '氏名']	process:9	thread:281472983924352
[ERROR]	2022-01-12 08:54:48,705	log	Internal Server Error: /peace_keeping/validate_serv/	process:9	thread:281472983924352
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "./peace_keeping/views/create_service_stock.py", line 32, in post
    serv_name, serv_items = ServiceStockForm.clean_fields(request.POST)
  File "./peace_keeping/forms/service_stock_form.py", line 26, in clean_fields
    serv_items = cls._clean_serv_items(inputs)
  File "./peace_keeping/forms/service_stock_form.py", line 58, in _clean_serv_items
    serv_item = Service_Item.objects.filter(phrase=_serv_item).get()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 439, in get
    raise self.model.DoesNotExist(
words.models.service_item.Service_Item.DoesNotExist: Service_Item matching query does not exist.
[DEBUG]	2022-01-12 09:10:31,361	service_stock	[base_url] http://127.0.0.1:8000	process:9	thread:281472983924352
[ERROR]	2022-01-12 09:10:31,459	log	Internal Server Error: /peace_keeping/get_needs/神奈川県相模原市/	process:9	thread:281472983924352
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 176, in render
    return self._render(context)
  File "/usr/local/lib/python3.8/site-packages/django/test/utils.py", line 101, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 977, in render
    return SafeString(''.join([
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 189, in render
    template = context.template.engine.select_template(template_name)
  File "/usr/local/lib/python3.8/site-packages/django/template/engine.py", line 200, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
django.template.exceptions.TemplateDoesNotExist: peace_keeping/used_service/modules/_fuzzy_search.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "./peace_keeping/views/register_used_service.py", line 23, in get
    return render(request, 'peace_keeping/used_service/get_needs.html', context)
  File "/usr/local/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: peace_keeping/used_service/modules/_fuzzy_search.html
[WARNING]	2022-01-12 09:10:31,465	load_papers	[WARNING] 未実装：保存前にサービスID、日付、入力内容の重複がないかバリデーションかける。	process:9	thread:281472983924352
[ERROR]	2022-01-12 09:10:31,489	log	Internal Server Error: /restore_order/load_papers/	process:9	thread:281472983924352
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "./restore_order/views/load_papers.py", line 38, in get
    paths = SelectCandidatesForm.get_file_paths(request.session['context']['area_name'])
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 50, in __getitem__
    return self._session[key]
KeyError: 'context'
[WARNING]	2022-01-12 09:32:39,622	load_papers	[WARNING] 未実装：保存前にサービスID、日付、入力内容の重複がないかバリデーションかける。	process:9	thread:281472983924352
[ERROR]	2022-01-12 09:32:39,686	log	Internal Server Error: /restore_order/load_papers/	process:9	thread:281472983924352
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "./restore_order/views/load_papers.py", line 38, in get
    paths = SelectCandidatesForm.get_file_paths(request.session['context']['area_name'])
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 50, in __getitem__
    return self._session[key]
KeyError: 'context'
[DEBUG]	2022-01-12 15:35:07,897	service_stock_form	[serv_name] 婚姻届	process:9	thread:281472983924352
[DEBUG]	2022-01-12 15:35:07,931	service_stock_form	[name] 婚姻届	process:9	thread:281472983924352
[DEBUG]	2022-01-12 15:35:08,058	service_stock_form	[serv_name] 婚姻届	process:9	thread:281472983924352
[DEBUG]	2022-01-12 15:35:08,060	service_stock_form	[_type] {'_type': 'serv_name'}	process:9	thread:281472983924352
[DEBUG]	2022-01-12 15:35:08,061	service_stock_form	[serv_items] ['神奈川県相模原市', '氏名']	process:9	thread:281472983924352
[ERROR]	2022-01-12 15:35:08,278	log	Internal Server Error: /peace_keeping/validate_serv/	process:9	thread:281472983924352
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "./peace_keeping/views/create_service_stock.py", line 32, in post
    serv_name, serv_items = ServiceStockForm.clean_fields(request.POST)
  File "./peace_keeping/forms/service_stock_form.py", line 26, in clean_fields
    serv_items = cls._clean_serv_items(inputs)
  File "./peace_keeping/forms/service_stock_form.py", line 58, in _clean_serv_items
    serv_item = Service_Item.objects.filter(phrase=_serv_item).get()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 439, in get
    raise self.model.DoesNotExist(
words.models.service_item.Service_Item.DoesNotExist: Service_Item matching query does not exist.
